
services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=root1234
    ports:
      - "1433:1433"
    networks:
      - mynetwork

  melkapi:
    build:
      context: .
      dockerfile: MelkYab.Backend/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=MelkYabDb;User=sa;Password=root1234;TrustServerCertificate=true;MultipleActiveResultSets=true
    ports:
      - "8080:8080"
    depends_on:
      - sqlserver
    networks:
      - mynetwork

networks:
  mynetwork:
